### ISSUE TITLE
Change team names to the names you would like them to be

### ISSUE THREAD

**Issue by zspencer** [tiger-swallowtails-2013/phase-2-guide#20]
In order to not have stupid greek names
As a Tiger Swallowtail
I would like to rename my team.md file

**Comment by johana-star** [comment]
It would makes sense to have them be five of some series. Like [superheroes](http://en.wikipedia.org/wiki/List_of_superhero_teams_and_groups)

**Comment by zspencer** [comment]
Only Gamma remains, once #30 is merged.
