### ISSUE TITLE
Book suggestion for Sinatra

### ISSUE THREAD

**Issue by SunnyIzr** [tiger-swallowtails-2013/phase-2-guide#22]
I would love a book on Sinatra!

**Comment by zspencer** [comment]
I've renamed the issue to be more specific (As there will always be new book suggestions ;))

**Comment by zspencer** [comment]
@SunnyIzr Here's a few links. Feel free to merge at will!

**Comment by johana-star** [comment]
We've got a PR for this, can we merge and mark as resolved?

**Comment by zspencer** [comment]
CLosing due to a week of inactivity.
